dataset:
  datasets_directory: "/big/chenye/code/RY-SlopeSearch/example/example_data/assembled-ecoli"

parameters:
  using_one_to_one_matching: true
  using_background_matches: false
  use_openmp: true

# methods
#   basic_kmer_matches
#   start_ry_matches
#   start_rr_matches
#   start_ry_4_6_matches
#   start_ry_4_9_matches
#   start_ry_4_push_matches
#   start_ry_4_pull_matches
#   start_ry_16_matches
#   start_ry_32_matches
#   start_ry_64_matches
#   start_ry_128_matches
sampling_method: "start_ry_128_matches"

draw_F_k_function: false
draw_k_max: 30 # if draw_F_k_function is true, the k_max will be used

output_directory: "/big/chenye/code/RY-SlopeSearch/example/example_output"

use_progress_bar: true
