dataset:
  datasets_directory: "/big/chenye/data/RY-SlopeSearch/af_project_dataset/AF-reference_datasets190511/genome-std-assembled-fish_mito/dataset/assembled-fish_mito"
# /big/chenye/data/RY-SlopeSearch/af_project_dataset/AF-reference_datasets190511/genome-std-assembled-fish_mito/dataset/assembled-fish_mito
# /big/chenye/data/RY-SlopeSearch/af_project_dataset/AF-reference_datasets190511/genome-std-assembled-ecoli/dataset/assembled-ecoli
# /big/chenye/data/RY-SlopeSearch/af_project_dataset/AF-reference_datasets190511/genome-std-assembled-plants/dataset/assembled-plants

parameters:
  using_one_to_one_matching: true
  using_background_matches: false
  use_openmp: true

# methods
#   basic_kmer_matches
#   start_ry_matches
#   start_ry_4_6_matches
#   start_ry_4_9_matches
#   start_ry_16_matches
#   start_ry_32_matches
#   start_ry_64_matches
#   start_ry_128_matches
sampling_method: "start_ry_matches"

output_directory: "/big/chenye/result/RY-SlopeSearch"

use_progress_bar: true
